// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlpkpvxckptjjdfexhzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscGtwdnhja3B0ampkZmV4aHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTc2ODcsImV4cCI6MjA2OTMzMzY4N30.uzVvY6elyIi91m7hs8CvRjfBBfL21ip0JkAWpyhoE3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});